apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: postal-codes-search-ingress
  namespace: workloads
spec:
  virtualhost:
    fqdn: postal-code-search.104.42.237.80.nip.io
    tls:
      secretName: postal-codes-search-cert
  routes:
  - conditions:
    - prefix: /
    services:
    - name: gateway-postal-codes
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postal-code-search-cert
  namespace: workloads
spec:
  commonName: postal-code-search.104.42.237.80.nip.io
  dnsNames:
  - postal-code-search.104.42.237.80.nip.io
  issuerRef:
    name: tap-ingress-selfsigned
    kind: ClusterIssuer
  secretName: postal-codes-search-cert
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: postal-codes-audit-ingress
  namespace: workloads
spec:
  virtualhost:
    fqdn: postal-code-audit.104.42.237.80.nip.io
    tls:
      secretName: postal-codes-audit-cert
  routes:
  - conditions:
    - prefix: /
    services:
    - name: gateway-postal-codes
      port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postal-codes-audit-cert
  namespace: workloads
spec:
  commonName: postal-code-audit.104.42.237.80.nip.io
  dnsNames:
  - postal-code-audit.104.42.237.80.nip.io
  issuerRef:
    name: tap-ingress-selfsigned
    kind: ClusterIssuer
  secretName: postal-codes-audit-cert
